name: Deploy

on:
  # Allow this workflow to be called from another repo (reusable workflow)
  workflow_call:
    inputs:
      initial_deploy:
        description: 'Whether this is an initial deploy (skip cache clear)'
        required: false
        type: boolean
        default: false
      theme:
        description: 'Theme name (e.g. lemon-theme) - if not provided, will auto-detect from web/app/themes directory'
        required: false
        type: string
      php_version:
        description: 'PHP version to use'
        required: false
        type: string
        default: '8.3'
      node_version:
        description: 'Node version to use'
        required: false
        type: string
        default: 'lts/*'
    secrets:
      SSH_KEY:
        description: 'SSH private key for deployment'
        required: true
      SSH_USER:
        description: 'SSH username for deployment'
        required: true
      SSH_HOST:
        description: 'SSH host for deployment'
        required: true

    
jobs:
  detect_theme:
    name: Detect Theme Name
    runs-on: ubuntu-latest
    outputs:
      theme_name: ${{ steps.detect-theme.outputs.THEME_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto-detect theme name
        id: detect-theme
        run: |
          if [ -n "${{ inputs.theme }}" ]; then
            echo "Using provided theme: ${{ inputs.theme }}"
            echo "THEME_NAME=${{ inputs.theme }}" >> $GITHUB_OUTPUT
          else
            echo "Auto-detecting theme from web/app/themes directory..."
            if [ -d "web/app/themes" ]; then
              # Get the first directory in web/app/themes (excluding . and ..)
              THEME_NAME=$(find web/app/themes -maxdepth 1 -type d ! -path web/app/themes | head -n 1 | xargs basename)
              if [ -n "$THEME_NAME" ]; then
                echo "Auto-detected theme: $THEME_NAME"
                echo "THEME_NAME=$THEME_NAME" >> $GITHUB_OUTPUT
              else
                echo "Error: No theme directory found in web/app/themes"
                exit 1
              fi
            else
              echo "Error: web/app/themes directory not found"
              exit 1
            fi
          fi

  build_php:
    name: Build PHP Dependencies (Initial Deploy Only)
    runs-on: ubuntu-latest
    needs: detect_theme
    if: inputs.initial_deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version || '8.3' }}
   
      - name: Install dependencies
        env:
          SATISPRESS_TOKEN: ${{ secrets.SATISPRESS_TOKEN }}
        run: |
          if [ -n "$SATISPRESS_TOKEN" ]; then
            composer config -a -g http-basic.packagist.studiolemon.nl \
            $SATISPRESS_TOKEN satispress
          else
            echo "Warning: No SATISPRESS_TOKEN found, skipping Satispress authentication"
          fi
          composer install --prefer-dist --no-progress

      - name: Cache PHP dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: php-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

  build_theme:
    name: Build Theme Assets
    runs-on: ubuntu-latest
    needs: detect_theme
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  
        with:
          node-version: ${{ inputs.node_version || 'lts/*' }}
          cache: 'yarn'
          cache-dependency-path: web/app/themes/${{ needs.detect_theme.outputs.theme_name }}/yarn.lock

      - name: Build theme assets
        run: |
          cd ./web/app/themes/${{ needs.detect_theme.outputs.theme_name }}
          cp ./resources/assets/config.json.example ./resources/assets/config.json
          # Replace 'wp-lemon-child' with actual theme name in config.json
          sed -i 's/wp-lemon-child/${{ needs.detect_theme.outputs.theme_name }}/g' ./resources/assets/config.json
          yarn install
          yarn run production

      - name: Cache built theme assets
        uses: actions/cache@v4
        with:
          path: web/app/themes/${{ needs.detect_theme.outputs.theme_name }}/dist/
          key: theme-${{ runner.os }}-${{ needs.detect_theme.outputs.theme_name }}-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}

  deploy_php:
    name: Deploy Bedrock and plugin PHP Files
    runs-on: ubuntu-latest
    needs: [detect_theme, build_php]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore PHP dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: php-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Deploy PHP files via rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --exclude=".*" --exclude="babel.config.js" --exclude="phpcs.xml" --exclude="*.code-workspace" --exclude="web/app/themes/${{ needs.detect_theme.outputs.theme_name }}"
          remote_path: files
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}


  deploy_theme:
    name: Deploy Theme Files
    runs-on: ubuntu-latest
    needs: [detect_theme, build_theme]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore built theme assets
        uses: actions/cache@v4
        with:
          path: web/app/themes/${{ needs.detect_theme.outputs.theme_name }}/dist/
          key: theme-${{ runner.os }}-${{ needs.detect_theme.outputs.theme_name }}-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}

      - name: Deploy theme files via rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --delete-excluded --exclude=".*" --exclude="babel.config.js" --exclude="package.json" --exclude="phpcs.xml.dist" --exclude="phpstan.neon.dist" --exclude="*.md" --exclude="yarn.lock" --exclude="package.lock" --exclude="node_modules"
          remote_path: files/web/app/themes/
          path: web/app/themes/${{ needs.detect_theme.outputs.theme_name }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
  clear_cache:
    name: Clear Cache
    runs-on: ubuntu-latest
    needs: [deploy_theme, deploy_php]
    if: inputs.initial_deploy
    steps:
      - name: Login and clear cache
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: 'cd files && wp spinupwp cache purge-site'

  deploy_env:
    name: Deploy Environment File (Initial Deploy Only)
    runs-on: ubuntu-latest
    needs: [detect_theme, deploy_php]
    if: inputs.initial_deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy and rename .env.example to .env
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr
          remote_path: files/.env
          path: .env.example
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
